Add compose exec_in_container method
testcontainers/testcontainers-python pull request #151
Opened 2021-07-15 22:11 UTC by kieranlea

This PR adds a method that reaches out to docker-compose to execute a command in a service container.

I'm open to suggestions, in particular on the return type. Having a 3 tuple undocumented seems like it may be unintuitive to understand, but there seems to already be precedent in the `get_logs` method above, and not seeing method docstrings there to document it.

Thanks

2022-04-02 15:38 UTC, yakimka approved these changes

2022-04-02 15:40 UTC, yakimka commented
@tillahoffmann, what do you think? Can we merge this?

2022-04-03 16:32 UTC, tillahoffmann requested changes
Let's add some documentation. I appreciate that some of the methods are poorly documented, but we should change that, too.

2022-04-03 19:22 UTC, kieranlea commented
> Let's add some documentation. I appreciate that some of the methods are poorly documented, but we should change that, too.

Agreed, thanks for reviewing the PR

2022-04-03 19:52 UTC, tillahoffmann commented on testcontainers/compose.py
> +        -------
```suggestion
        ----------
```

2022-04-03 19:52 UTC, tillahoffmann approved these changes

2022-04-03 20:09 UTC, merged

2022-04-03 20:09 UTC, tillahoffmann commented
Merged after unrelated test failure.