Support specifying postgresql drivers
testcontainers/testcontainers-python pull request #156
Opened 2021-09-25 09:11 UTC by KarolisL

2021-09-25 09:14 UTC, KarolisL commented
Btw, I wasn't able to quickly google the docstring format. Would you please point me to the spec so I could format the docstring properly? https://github.com/testcontainers/testcontainers-python/pull/156/files#diff-0d0163aaa012beed78914f91926197b1bd2fcd7fc84eaa6bf345367f2860d8cdR30

2022-04-02 15:18 UTC, yakimka requested changes

2022-04-02 15:18 UTC, yakimka commented on testcontainers/postgres.py
> +    ::
I think that it is not necessary to change the example in the docstring.

2022-04-03 17:01 UTC, tillahoffmann commented on setup.py
> +        'postgresql-pg8000': ['sqlalchemy', 'pg8000'],
```suggestion```

Users can install different drivers independently.

2022-04-04 19:29 UTC, yakimka commented
@KarolisL, please fix formatting

2022-04-04 19:56 UTC, yakimka approved these changes

2022-04-04 19:57 UTC, merged