Issue 336
testcontainers/testcontainers-python pull request #340
Opened 2023-04-23 15:48 UTC by logicbomb

I decided to include both the log check & the `pg_isready` check, as it seems they both need to be successful in order to enure the database is running.  

I don't think the `driver` parameter  belongs in `Postgres.__init__` method, as it's only used when building the connection string, but I didn't want to introduce any breaking changes.

Also, I am pretty new to python and was having trouble adding my fork of the project as a package to an external test project. It would be nice if there were some guidance on that in the README.  I tried following the instructions in both the `poetry` and `pip` documentation, but couldn't install from github as there is neither `setup.py`  nor `pyproject.toml` in the root directory.

2023-05-05 22:03 UTC, tillahoffmann requested changes
Thanks for the contribution. Do you think we can achieve the same outcome by overriding `_connect` for the postgres container and moving the content of `_verify_status` into `_connect`?

2023-05-11 20:27 UTC, jankatins commented on README.rst
> -    >>> with PostgresContainer("postgres:9.5") as postgres:
According to https://www.postgresql.org/support/versioning/, 9.5 is not supported anymore, the oldest supported version is 11. My suggestion would be to go with 15 and then have another 5 years until the docs have to be changed... :-)

2023-05-11 20:33 UTC, jankatins commented on postgres/tests/test_postgres.py
> +    supported_versions = ["11", "12", "13", "14", "latest"]
15 is current

2023-05-11 20:50 UTC, tillahoffmann commented on README.rst
> -    >>> with PostgresContainer("postgres:9.5") as postgres:
Makes sense, let's bump to 15.

2023-08-29 17:04 UTC, nicos68 commented
Hi,

any idea when this could be merged ? I’m using peewee as my orm and would love to get rid of that too.

2023-10-19 16:04 UTC, jankatins commented
This could also remove the hard dependency on psycopg2 which is slowly superseded by psycopg (v3). At least for us it's now the only package which pulls in the psycopg2 binary :-/

2023-10-19 16:10 UTC, jankatins requested changes
This actually needs to remove the dependencies on sqlalchemy and psycopg2

2024-01-23 12:55 UTC, jankatins commented on README.rst
> -    >>> with PostgresContainer("postgres:9.5") as postgres:
... so now 16 :-)

2024-02-20 15:13 UTC, dvuletas commented
When this would be expected to be merged? 
Thanks!

2024-02-28 13:09 UTC, jankatins commented
@logicbomb  Will you find time to get this running on top of the current main branch? If not: would you mind if I take this and rebase (or rework, if needed) and open it as a new PR (I will keep your handle as co-author on the commit)?

2024-03-04 09:31 UTC, totallyzen commented
> If not: would you mind if I take this and rebase (or rework, if needed) and open it as a new PR (I will keep your handle as co-author on the commit)?

Thanks for the activity, mate! I personally wouldn't mind you taking this on (my default attitude is "people are long gone" unless proven otherwise).



However, if I could ask for a tweak :innocent: :pleading_face: 

- Make it not be in `generic.py`. These "db containers" assume a certain URL format, but is it worth it to have an entire class just for this? (I won't hide my distaste over `DbContainer` and why it is in `core` in the first place)
- It's possible the same thing as for `kafka`, I would be happy with that approach, see #377

2024-03-04 10:09 UTC, jankatins commented
> Make it not be in generic.py. These "db containers" assume a certain URL format, but is it worth it to have an entire class
> just for this? (I won't hide my distaste over DbContainer and why it is in core in the first place)

So what's the alternative (in the order of my preference, best to lowest)?

- Move it to a different file?
- Make all the db container implement ´_create_connection_url()`?
- Add a different layer, like singledispatch to turn the container into an URL?

> It's possible the same thing as for kafka, I would be happy with that approach, see
> https://github.com/testcontainers/testcontainers-python/pull/377

This is exactly what this PR does :-) It uses both logs and pg_isready to check instead of opening a connection. It's still missing that the dependency can be removed.

2024-03-06 20:59 UTC, jankatins commented
I opened https://github.com/testcontainers/testcontainers-python/pull/445 for the rebased version.

2024-03-09 14:27 UTC, alexanderankin commented
closing in favor of #445 for now

2024-03-09 14:27 UTC, closed without merging