fix(core): Typed docker_client
testcontainers/testcontainers-python pull request #702
Opened 2024-09-16 05:59 UTC by Tranquility2

Supports: https://github.com/testcontainers/testcontainers-python/issues/305
Related : https://github.com/testcontainers/testcontainers-python/pull/691 https://github.com/testcontainers/testcontainers-python/pull/692 #700 

Based on #504, kudos @alexanderankin 

```
poetry run mypy --config-file pyproject.toml core/testcontainers/core/docker_client.py 
Success: no issues found in 1 source file
```

Old
```
                    Error Summary                     
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┓
┃ File Path                                 ┃ Errors ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━┩
│ core/testcontainers/core/version.py       │ 12     │
│ core/testcontainers/core/docker_client.py │ 14     │
│ core/testcontainers/core/image.py         │ 17     │
│ core/testcontainers/core/waiting_utils.py │ 8      │
│ core/testcontainers/core/container.py     │ 20     │
│ core/tests/test_new_docker_api.py         │ 4      │
│ core/tests/test_docker_in_docker.py       │ 2      │
│ core/testcontainers/compose/compose.py    │ 22     │
│ core/testcontainers/compose/__init__.py   │ 2      │
│ core/tests/test_version.py                │ 2      │
│ core/tests/test_ryuk.py                   │ 2      │
│ core/tests/test_registry.py               │ 1      │
│ core/tests/test_image.py                  │ 3      │
│ core/tests/test_compose.py                │ 7      │
└───────────────────────────────────────────┴────────┘
Found 116 errors in 14 files.
```
New
```
                    Error Summary                     
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┓
┃ File Path                                 ┃ Errors ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━┩
│ core/testcontainers/core/version.py       │ 12     │
│ core/testcontainers/core/network.py       │ 3      │
│ core/testcontainers/core/image.py         │ 17     │
│ core/testcontainers/core/waiting_utils.py │ 8      │
│ core/testcontainers/core/container.py     │ 19     │
│ core/tests/test_new_docker_api.py         │ 4      │
│ core/tests/test_docker_in_docker.py       │ 2      │
│ core/testcontainers/compose/compose.py    │ 22     │
│ core/testcontainers/compose/__init__.py   │ 2      │
│ core/tests/test_version.py                │ 2      │
│ core/tests/test_ryuk.py                   │ 2      │
│ core/tests/test_registry.py               │ 1      │
│ core/tests/test_image.py                  │ 3      │
│ core/tests/test_compose.py                │ 7      │
└───────────────────────────────────────────┴────────┘
Found 104 errors in 14 files.
```

2024-11-16 09:39 UTC, Tranquility2 commented
Please note 
```core/testcontainers/core/config.py:46: error: X | Y syntax for unions requires Python 3.10  [syntax]
        connection_mode: str | None = environ.get("TESTCONTAINERS_CONNECTION_MODE")```
Found when rebasing.

2024-12-14 18:29 UTC, Tranquility2 commented
@alexanderankin @kiview can you please rerun this? (I assume this was an issue with the docker registry)

2025-02-28 13:01 UTC, CarliJoy requested changes
Please use `cast` only when required (i.e. for `dict[str, Any]`).

If possible always improve the runtime type safety.

2025-03-08 22:32 UTC, Tranquility2 commented
@CarliJoy apricate you taking the time to comment :) I'll be happy to fix.
I assume/hope https://github.com/testcontainers/testcontainers-python/pull/700 & https://github.com/testcontainers/testcontainers-python/pull/701 will go in **first** so I'll know we are really rolling with this track.

2025-03-15 10:07 UTC, Tranquility2 commented on core/testcontainers/core/config.py
> +        if cast(str, self) == self.bridge_ip:
@CarliJoy Mypy seems to disagree:
![image](https://github.com/user-attachments/assets/64dd87b5-5e98-4af2-a802-622e58752c75)

2025-03-15 10:08 UTC, Tranquility2 commented on core/testcontainers/core/config.py
> +        if cast(str, self) == self.bridge_ip:
I understand the usage of the playground but please run it locally with context 
```poetry run mypy --config-file pyproject.toml core/testcontainers/core/docker_client.py```

2025-03-15 10:20 UTC, Tranquility2 commented on core/testcontainers/core/config.py
> +        if cast(str, self) == self.bridge_ip:
Update to latest mypy, still the same behavior

2025-03-15 10:33 UTC, Tranquility2 commented on core/testcontainers/core/config.py
> +        if cast(str, self) == self.bridge_ip:
Found the issue :)
under "[tool.mypy]" on pyproject.toml
we have ```strict = true``` 
I'll be adding 
```# type: ignore[comparison-overlap]``` in the relevant locations @CarliJoy

2025-03-15 10:35 UTC, Tranquility2 commented on core/testcontainers/core/config.py
> +        if cast(str, self) == self.bridge_ip:
Fixed

2025-03-15 10:36 UTC, Tranquility2 commented on core/testcontainers/core/docker_client.py
> +        return cast(str, container["NetworkSettings"]["Networks"][network_name]["IPAddress"])
Fixed

2025-03-15 10:38 UTC, Tranquility2 commented on core/testcontainers/core/docker_client.py
> +        return cast(str, name)
super nice, fixed

2025-03-15 10:39 UTC, Tranquility2 commented on core/testcontainers/core/docker_client.py
> +        return cast(str, container["NetworkSettings"]["Networks"][network_name]["Gateway"])
Fixed

2025-03-15 10:46 UTC, Tranquility2 commented on core/testcontainers/core/docker_client.py
> +            return cast(str, url.hostname)
This is great, but `url.hostname` is still "Any" and we expects "str"

2025-03-15 10:51 UTC, Tranquility2 commented on core/testcontainers/core/docker_client.py
> +            return cast(str, url.hostname)
Fixed

2025-03-15 10:59 UTC, Tranquility2 commented
@CarliJoy Update with all of the Fixes

2025-03-15 12:25 UTC, CarliJoy commented on core/testcontainers/core/config.py
> +        if cast(str, self) == self.bridge_ip:
`        if self == ConnectionMode.bridge_ip:`

Seems to be the type correct solution.

2025-04-11 11:31 UTC, Tranquility2 commented on core/testcontainers/core/config.py
> +        if cast(str, self) == self.bridge_ip:
Will fix after https://github.com/testcontainers/testcontainers-python/pull/807 as it also touch this part :)

2025-05-04 17:57 UTC, alexanderankin approved these changes

2025-05-04 17:57 UTC, merged